---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: "standard"
